app:
  logFile: log/gin.log
  httpPort: 8080
  webSocketPort: 8089
  rpcPort: 9001
  httpUrl: 127.0.0.1:8080
  webSocketUrl: 127.0.0.1:8089
  
redis:
  addr: 127.0.0.1:6379
  password: ""
  db: 0
  poolSize: 30
  minIdleConns: 30