name: 尝试将项目部署在github pages上

on: 
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  Go-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set gp version
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          


      - name: install dependent
        run: go mod download 
      
      - name: Build
        run: go build -o test

      - name: Test
        run: ./test
    
      # - name: 部属page
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: ./views/home
